# .github/workflows/keepalive.yml
name: Keep Alive

on:
  schedule:
    - cron: '0 0 * * *' # chạy mỗi ngày 0:00 UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep repo alive
        run: echo "Still alive at $(date)"
